USERNAME ?= $(shell bash -c 'read -p "Username: " username; echo $$username')
PASSWORD ?= $(shell bash -c 'read -s -p "Password: " pwd; echo $$pwd')

test:  
	@clear
	@echo Username › $(USERNAME)
	@echo Password › $(PASSWORD)