// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "users/internal/handler/user"
	"users/internal/svc"
	health "users/internal/handler/health"
	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:id",
				Handler: user.UsersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user",
				Handler: user.UserGetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: health.HealthHandler(serverCtx),
			},
		},
	)
}
